language: go
go:
- latest
before_install:
- go get github.com/mitchellh/gox
- go get github.com/gorilla/mux
- go get gopkg.in/validator.v2
- go get github.com/justinas/alice
script:
- go test ./...
after_success:
- gox -output="bin/{{.Dir}}_{{.OS}}_{{.Arch}}" -os="linux windows darwin"
deploy:
  provider: releases
  api_key:
    secure: Wg5VRE7uF9rSm1vLRElMfOknC//rEuApY+tR8Qb5CYZuLcZMuM/Jz5G5fPopKEqBGndpGhrXxImU9CHCior1oLVr0HXb0HIc2w4G4EFdjNZ3ftAdgZktZQI1LaA3kUbN7GxVet9cZLYtiGMMukwJxlUVY7su6H2LGVdd/lXI0x5JMYZx1/xC/IX5xVL85gzRwvWzIbVXcDMikwtHuBlWRXldjy6XD4VpUO4BLKNjdJ2ISPVkgMFOtb40pjRR0OWZlNF7NIFD9ATRtCBqzHcaWCUMT1v8d/RIyqpfeBKdX5ZglJt7KCqUyGohmJW4w2V9V5mcZzJyLYrWikRIy50pSG1iYnwrvwO1ws2l3lqtRjQ7vZ5Kr7rhDc4m3aUM7QIGpV6ULq+3Srde7eN2r20pMnfpe5H/45tteDDcnRt6300AA02MoglPOBTOcwg+PuAWZPyPggPw7mOaV3sRmI+rhHZHxyNBuIE7J/RwyKfkhMdbWkdRki9QxUPg6hIDGMtKqKYemDp6LmyqYlr+60/Xzj+CzP2CtQ0j9a/fVEA6ugTjFqCK8NvToUUxdCu0o5rvm7F73f1au6QmtIV9KiXdj8DoA5ojSutAaPkmq8+2lFxdjyjChD1Gm7CddAzr/QLWDw0BuRieXcrey/DYntg+chWtb7HQjmAyfch2COHnvhk=
  file_glob: true
  file: bin/*
  skip_cleanup: true
  on:
    tags: true
    repo: gitu/force
