package main

//This file is auto-generated by go-raml
//Do not edit this file by hand since it will be overwritten during the next generation

import (
	"github.com/gorilla/mux"
	"net/http"
)

// EntriesInterface is interface for /entries root endpoint
type EntriesInterface interface { // Get is the handler for GET /entries
	Get(http.ResponseWriter, *http.Request)
}

// EntriesInterfaceRoutes is routing for /entries root endpoint
func EntriesInterfaceRoutes(r *mux.Router, i EntriesInterface) {
	r.HandleFunc("/entries", i.Get).Methods("GET")
}
