package main

//This file is auto-generated by go-raml
//Do not edit this file by hand since it will be overwritten during the next generation

import (
	"github.com/gorilla/mux"
	"net/http"
)

// GroupsInterface is interface for /groups root endpoint
type GroupsInterface interface { // Get is the handler for GET /groups
	Get(http.ResponseWriter, *http.Request)
}

// GroupsInterfaceRoutes is routing for /groups root endpoint
func GroupsInterfaceRoutes(r *mux.Router, i GroupsInterface) {
	r.HandleFunc("/groups", i.Get).Methods("GET")
}
