#%RAML 1.0
title: FORCe API
baseUri: http://localhost:5000/

mediaType: application/json

types:
  Group:
    type: object
    properties:
      id: string
      name: string
  Groups:
    type: Group[]
    minItems: 0
    uniqueItems: true
    example:
      - id: KDO
        name: Kommando
      - id: Z1
        name: Zug 1
      - id: PN1
        name: Pikett Nacht 1
  Entry:
    type: object
    properties:
      name: string
      group: Group
      alternativeGroup?:
        type: string
        description: all with the same alternativeGroup are alternative entries
      start: datetime
      end: datetime
      type:
        type: string
        enum: [mandatory, optional, standby]
    example:
      name: 1. Uebung Zug 1"
      start: 2018-03-03T20:30:00Z
      end: 2018-03-03T22:30:00Z
      alternativeGroup: 2018-ZU1
      group:
        id: Z1
        name: Zug 1
      type: mandatory


/groups:
  description: Groups of people
  get:
    responses:
      200:
        body:
          type: Groups
  /{groupId}:
    get:
      description: Gets a list of all entries for this group
      responses:
        200:
          body:
            type: Entry[]

/entries:
  description: Date Entries of relevance
  get:
    queryParameters:
       groupIds:
         description: A list of groupIds
         type: array
         items:
           type: string
           minLength: 1
         uniqueItems: true
    responses:
      200:
        body:
          type: Entry[]



